import { GeoPreset } from "./types.js";

export const GEO_PRESETS: GeoPreset[] = [
  {
    id: "preset:ai_services",
    name: "AI & LLM Services (OpenAI, Claude, Perplexity, Copilot)",
    category: "ai",
    description: "Major AI development and chat platforms",
    domains: [
      "openai.com",
      "*.openai.com",
      "chatgpt.com",
      "*.chatgpt.com",
      "anthropic.com",
      "*.anthropic.com",
      "claude.ai",
      "*.claude.ai",
      "perplexity.ai",
      "*.perplexity.ai",
      "huggingface.co",
      "*.huggingface.co",
      "githubcopilot.com",
      "*.githubcopilot.com",
      "midjourney.com",
      "*.midjourney.com",
      "gemini.google.com",
      "*.gemini.google.com",
      "aistudio.google.com",
      "*.aistudio.google.com",
      "generativelanguage.googleapis.com",
      "alkalimining-pa.googleapis.com",
      "proactivebackend-pa.googleapis.com",
      "deepmind.google",
      "*.deepmind.google",
      "labs.google",
      "*.labs.google",
      "notebooklm.google.com",
      "ai.google.dev",
      "*.ai.google.dev",
      "antigravity.google",
      "*.antigravity.google",
    ],
  },
  {
    id: "preset:social_media",
    name: "Global Media & Social (X/Twitter, LinkedIn, YouTube, Meta)",
    category: "social",
    description: "International social networks and video platforms",
    domains: [
      "x.com",
      "*.x.com",
      "twitter.com",
      "*.twitter.com",
      "twimg.com",
      "*.twimg.com",
      "instagram.com",
      "*.instagram.com",
      "facebook.com",
      "*.facebook.com",
      "linkedin.com",
      "*.linkedin.com",
      "youtube.com",
      "*.youtube.com",
      "googlevideo.com",
      "*.googlevideo.com",
    ],
  },
  {
    id: "preset:corporate_internal",
    name: "Corporate Intranet & Private RFC1918 Subnets",
    category: "internal",
    description: "Internal domains and private network ranges (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16)",
    domains: [
      "*.local",
      "*.corp.local",
      "*.internal",
      "localhost",
      "127.0.0.1",
      "10.0.0.0/8",
      "172.16.0.0/12",
      "192.168.0.0/16",
    ],
  },
  {
    id: "preset:geosite_ru",
    name: "Geo: Russia (.RU / .РФ / Yandex / VK / Gosuslugi)",
    category: "ru",
    description: "National Russian domain zone and state/banking services",
    domains: [
      "*.ru",
      "*.su",
      "*.xn--p1ai",
      "*.yandex.ru",
      "*.ya.ru",
      "*.vk.com",
      "*.mail.ru",
      "*.gosuslugi.ru",
      "*.sberbank.ru",
      "*.tinkoff.ru",
      "*.ozon.ru",
      "*.wildberries.ru",
    ],
  },
  {
    id: "preset:ad_telemetry_block",
    name: "Security: Ads, Trackers & Malicious Telemetry Sinkhole",
    category: "security",
    description: "Common tracking, telemetry, and advertising networks to sinkhole",
    domains: [
      "*.doubleclick.net",
      "*.google-analytics.com",
      "*.adservice.google.com",
      "*.telemetry.corp",
      "*.adnxs.com",
      "*.scorecardresearch.com",
    ],
  },
  {
    id: "preset:ip_check",
    name: "IP & Network Verification (ipify, icanhazip, 2ip, ifconfig.me)",
    category: "diagnostics",
    description: "External IP verification tools routed through proxy to verify tunnel exit IP",
    domains: [
      "api.ipify.org",
      "*.api.ipify.org",
      "ipify.org",
      "*.ipify.org",
      "icanhazip.com",
      "*.icanhazip.com",
      "ifconfig.me",
      "*.ifconfig.me",
      "ipinfo.io",
      "*.ipinfo.io",
      "2ip.io",
      "*.2ip.io",
      "2ip.ru",
      "*.2ip.ru",
      "whatismyipaddress.com",
      "*.whatismyipaddress.com",
      "whoer.net",
      "*.whoer.net",
      "checkip.amazonaws.com",
      "ip-api.com",
      "*.ip-api.com",
      "speedtest.net",
      "*.speedtest.net",
      "myip.is",
      "*.myip.is",
      "ip.me",
      "*.ip.me",
    ],
  },
];
